force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Item</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Stock Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of the item.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <description>Name of the Stock Item (eg. 18&quot; Paella Pan)</description>
    <inlineHelpText>Name of the Stock Item (eg. 18&quot; Paella Pan)</inlineHelpText>
    <label>Item Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Minimum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Stock_Level__c</fullName>
    <inlineHelpText>The minimum amount we should keep in stock for this item.  Reorder when this threshold is met.</inlineHelpText>
    <label>Minimum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StockItemHandler_Test.cls
@isTest
private class StockItemHandler_Test {
    
    @isTest static void testBeforeInsertFunctionality() {
        // Implement test code
    }
    
    @isTest static void testBeforeDeleteFunctionality() {
        // Implement test code
    }

    @isTest static void testGetLowStockItems() {
        // Implement test code
    }

    @isTest static void packageUploadCoverage() {
        Stock_Item__c item = new Stock_Item__c();
        item.Item_Name__c = 'Test';
        item.Description__c = 'Test';
        item.Minimum_Stock_Level__c =3;

        insert item;

    }
    
}