force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Item</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Stock Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of the item.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <description>Name of the Stock Item (eg. 18&quot; Paella Pan)</description>
    <inlineHelpText>Name of the Stock Item (eg. 18&quot; Paella Pan)</inlineHelpText>
    <label>Item Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Minimum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Stock_Level__c</fullName>
    <inlineHelpText>The minimum amount we should keep in stock for this item.  Reorder when this threshold is met.</inlineHelpText>
    <label>Minimum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Stock_on_Hand__c.field-meta.xml
<CustomField>
    <fullName>Stock_on_Hand__c</fullName>
    <label>Stock on Hand</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CompletedStockItem.cls
/**
 * Object Oriented Class that represents our Stock_Item__c Object and provides functionality 
 */
public with sharing class CompletedStockItem {

    public String id;
    public String name;
    public String description;
    public Decimal listPrice;
    public Integer minStockLevel;
    public Integer stockOnHand;

    /**
     * Class constructor.
     */
    public CompletedStockItem(String itemName, String itemDescription, Decimal itemPrice, Integer itemMinStock, Integer itemStockOnHand) {
        name = itemName;
        description = itemDescription;
        listPrice = itemPrice;
        minStockLevel = itemMinStock;
        stockOnHand = itemStockOnHand;
    }

    public void create () {

        Stock_Item__c item = new Stock_Item__c ();
        item.Item_Name__c = name;
        item.Description__c = description;
        item.List_Price__c = listPrice;
        item.Minimum_Stock_Level__c = minStockLevel;
        item.Stock_on_Hand__c = stockOnHand;
        insert item;

    }

}