force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Item</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Stock Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of the item.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <description>Name of the Stock Item (eg. 18&quot; Paella Pan)</description>
    <inlineHelpText>Name of the Stock Item (eg. 18&quot; Paella Pan)</inlineHelpText>
    <label>Item Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Minimum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Stock_Level__c</fullName>
    <inlineHelpText>The minimum amount we should keep in stock for this item.  Reorder when this threshold is met.</inlineHelpText>
    <label>Minimum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ItemCollection.cls
public with sharing class ItemCollection {

	public List < Item > itemList;

	//Constructor, takes a list of Items and assigns them to the class for processing
	public ItemCollection(List < Item > items) {
		this.itemList = items;
	}
	
	public void insertItemSobjects () {

		//New list of Stock Item objects to be inserted 
		List < Stock_Item__c > itemSobjects = new List < Stock_Item__c >();

		//Loop through the list of items, creating a coresponding SObject for each
		for (Item i: this.itemList) {
			Stock_Item__c stockItem = new Stock_Item__c();
			stockItem.Item_Name__c = i.name;
	        stockItem.List_Price__c = i.listPrice;
	        stockItem.Description__c = i.description;
	        stockItem.Minimum_Stock_Level__c = i.minimumStockNeeded;

	        //Add the object to the insert list
	        itemSobjects.add(stockItem);
		}

		//Insert the sobjects
		System.debug('objects to insert: '+itemSobjects);
		insert itemSobjects;

	}

}