force-app/main/default/objects/Stock_Item__c/Stock_Item__c.object-meta.xml
<CustomObject>
    <label>Stock Item</label>
    <nameField>
        <displayFormat>SI-{00000}</displayFormat>
        <label>Stock Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stock Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>Description of the item.</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Item_Name__c.field-meta.xml
<CustomField>
    <fullName>Item_Name__c</fullName>
    <description>Name of the Stock Item (eg. 18&quot; Paella Pan)</description>
    <inlineHelpText>Name of the Stock Item (eg. 18&quot; Paella Pan)</inlineHelpText>
    <label>Item Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Stock_Item__c/fields/Minimum_Stock_Level__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Stock_Level__c</fullName>
    <inlineHelpText>The minimum amount we should keep in stock for this item.  Reorder when this threshold is met.</inlineHelpText>
    <label>Minimum Stock Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Item.cls
//Object Oriented Class that defines and provides functions for operating on an Item.
//This is sometimes called a Wrapper class, since it corresponds to an SObject in our Salesforce org.
public with sharing class Item {

    public Decimal listPrice; // ex  3.4 signifies $3.40
    public String name;
    public String description;
    public Integer minimumStockNeeded;

    //Constructor: Used when initializing the class, sets values for our Item object
    public Item(Decimal price, String itemName, String itemDescription, Integer minStock) {
        //set class variables
        listPrice = price;
        name = itemName;
        description = itemDescription;
        minimumStockNeeded = minStock;

    }

    //Inserts a corresponding Stock_Item__c object in our database
    public void insertItemSObject () {
        Stock_Item__c  stockItem = new Stock_Item__c();
        stockItem.Item_Name__c = this.name;
        stockItem.List_Price__c = this.listPrice;
        stockItem.Description__c = this.description;
        stockItem.Minimum_Stock_Level__c = this.minimumStockNeeded;

        insert stockItem;

    }

}